package br.org.cac.repositories;

import java.util.Date;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import br.org.cac.models.Colaborador;
import br.org.cac.models.Doacao;

/**
* Generated by Spring Data Generator on 16/03/2019
*/
@Repository
public interface DoacaoRepository extends JpaRepository<Doacao, Integer>, JpaSpecificationExecutor<Doacao> {
	
	Page<Doacao> findByColaboradorNomeContainingOrCadastro(String nome, Date cadastro, Pageable pageable);
	Page<Doacao> findByColaborador(Colaborador colaborador, Pageable pageable);

}
