package br.org.cac.repositories;

import java.util.Date;
import java.util.List;
import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import br.org.cac.models.Colaborador;
import br.org.cac.models.Doacao;

/**
* Generated by Spring Data Generator on 16/03/2019
*/
@Repository
public interface DoacaoRepository extends JpaRepository<Doacao, Integer>, JpaSpecificationExecutor<Doacao> {
	
	Page<Doacao> findByColaboradorNomeContainingOrCadastro(String nome, Date cadastro, Pageable pageable);
	
	Page<Doacao> findByColaboradorNomeContainingAndCadastro(String nome, Date cadastro, Pageable pageable);
	
	Page<Doacao> findByColaboradorNomeContainingAndCadastroBetween(String nome, Date dataInicial, Date dataFinal, Pageable pageable);
	
	Page<Doacao> findByColaboradorNomeContaining(String nome, Pageable pageable);
	
	Page<Doacao> findByCadastro(Date cadastro, Pageable pageable);
	
	Page<Doacao> findByCadastroBetween(Date dataInicial, Date dataFinal, Pageable pageable);
	
	List<Doacao> findByCadastro(Date cadastro);
	
	Page<Doacao> findByColaboradorNomeOrCadastro(Optional<String> nome, Date cadastro, Pageable pageable);
	

}
