package br.ord.cac.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.stereotype.Repository;

import br.ord.cac.models.Colaborador;

/**
* Generated by Spring Data Generator on 16/03/2019
*/
@Repository
@RepositoryRestResource(path="colaboradores")
public interface ColaboradorRepository extends JpaRepository<Colaborador, Integer>, JpaSpecificationExecutor<Colaborador> {

}
