package br.ord.cac.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import br.ord.cac.models.ItemDoacao;

/**
* Generated by Spring Data Generator on 16/03/2019
*/
@Repository
public interface ItemDoacaoRepository extends JpaRepository<ItemDoacao, Integer>, JpaSpecificationExecutor<ItemDoacao> {

}
